### ISSUE TITLE
champ_base dependency issue

### ISSUE THREAD

**Issue by robot-park** [jediofgever/quadruped_ros2#2]
Have issue on dependecies in champ_base
quadruped_ros2/champ_base/include/quadruped_controller.hpp:33:10: fatal error: champ_msgs/msg/Joints.msg:.~~~~

**Comment by roboticswithjulia** [comment]
Hello, did you be able to run this repository? I am facing some issues with the urdf, I can only get one leg in the joint_states. The issue comes as the TF tree cannot be constructed well.   Thank you! I changed something to be able to build the package with humble, here is my forked repository https://github.com/roboticswithjulia/quadruped_ros2. Thank you!
![Screenshot from 2024-07-30 02-34-23](https://github.com/user-attachments/assets/0a9f4b89-3a11-4f03-8cf8-10ed7e3024ea)
